### ISSUE TITLE
avoid duplicate content

### ISSUE THREAD

**Issue by lassediercks** [afknapping/xafknapping.github.io#13]
[the headline](https://github.com/filtercake/filtercake.github.io/blob/master/index.html#L304) with this css:

```css
h1::before,
h1::after {
  content: attr(data-text);
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
```

means for a screenreader:

Hi I'm fabian, Hi I'm Fabian, Hi I'm Fabian
